---
swagger: '2.0'
info:
  title: Book Appointment API
  version: v1
  description: This API is a backend for a tablet web-app that will enable sports
    athletes(users) to book an appointment with a physiotherapist doctor
paths:
  "/appointments":
    post:
      summary: Create a new appointment
      tags:
      - User
      consumes:
      - application/json
      parameters:
      - name: appointment
        in: body
        schema:
          user_id:
            type: integer
          doctor_id:
            type: integer
          description:
            type: string
          appointment_date:
            type: string
          appointment_time:
            type: string
        description: a new appointment param to be added
        required:
        - user_id
        - doctor_id
        - description
        - appointment_date
        - appointment_time
      responses:
        '200':
          description: new appointment created
          examples:
            application/json:
              user_id: 1
              doctor_id: 2
              description: This is my first appointment
              appointment_date: '2020-03-24'
              appointment_time: '2020-02-24 17:48:44 +0000'
        '422':
          description: invalid request
          schema:
            "$ref": "#/definitions/invalid_request_error"
basePath: "/api/v1"
definitions:
  doctor:
    type: object
    properties:
      id:
        type: integer
      firstname:
        type: string
      lastname:
        type: string
      email:
        type: string
      username:
        type: string
      city:
        type: string
  appointment:
    type: object
    properties:
      id:
        type: integer
      doctor_firstname:
        type: string
      doctor_lastname:
        type: string
      doctor_email:
        type: string
      username:
        type: string
      email:
        type: string
      date_of_appointment:
        type: string
      time_of_appointment:
        type: string
      description:
        type: string
  not_found_error:
    type: object
    properties:
      message:
        type: string
  invalid_request_error:
    type: object
    properties:
      message:
        type: string
