---
swagger: '2.0'
info:
  title: Book Appointment API
  version: v1
  description: This API is a backend for a tablet web-app that will enable sports
    athletes(users) to book an appointment with a physiotherapist doctor
paths:
  "/doctors":
    get:
      summary: Retrieves a list of doctors
      tags:
      - User
      produces:
      - application/json
      responses:
        '200':
          description: returns list of doctors
          examples:
            application/json:
              id: 1
              firstname: Jerry
              lastname: Christian
              email: jerry.c@bco.com
              username: jerryC123
              city: LA
          schema:
            type: array
            items:
              "$ref": "#/definitions/doctor"
            required:
            - id
            - username
            - email
            - firstname
            - lastname
            - city
  "/doctors/{id}":
    get:
      summary: Retrieves a doctor
      tags:
      - User
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        type: integer
        description: pass an id for the doctor
        required: true
      responses:
        '200':
          description: doctor found
          schema:
            "$ref": "#/definitions/doctor"
            required:
            - id
            - username
            - email
            - firstname
            - lastname
            - city
        '400':
          description: record not found
          schema:
            "$ref": "#/definitions/not_found_error"
  "/doctors/{doctor_id}/appointments":
    get:
      summary: Retrieves a list of doctor's appointments
      tags:
      - Doctor
      produces:
      - application/json
      parameters:
      - name: doctor_id
        in: path
        type: integer
        description: retrieve all appointments belonging to this id
        required: true
      responses:
        '200':
          description: doctor's appointments found
          schema:
            type: array
            items:
              "$ref": "#/definitions/appointment"
            required:
            - id
            - username
            - email
            - doctor_firstname
            - doctor_lastname
            - doctor_email
            - date_of_appointment
            - time_of_appointment
            - description
        '400':
          description: record not found
          schema:
            "$ref": "#/definitions/not_found_error"
  "/doctors/{doctor_id}/appointments/{id}":
    get:
      summary: Retrieves a single doctor's appointment
      tags:
      - Doctor
      produces:
      - application/json
      parameters:
      - name: doctor_id
        in: path
        type: integer
        description: the doctor's id
        required: true
      - name: id
        in: path
        type: integer
        description: retrieve a single appointment with id belonging to doctor
        required: true
      responses:
        '200':
          description: doctor's appointment found
          schema:
            "$ref": "#/definitions/appointment"
            required:
            - id
            - username
            - email
            - doctor_firstname
            - doctor_lastname
            - doctor_email
            - date_of_appointment
            - time_of_appointment
            - description
        '400':
          description: record not found
          schema:
            "$ref": "#/definitions/not_found_error"
basePath: "/api/v1"
definitions:
  doctor:
    type: object
    properties:
      id:
        type: integer
      firstname:
        type: string
      lastname:
        type: string
      email:
        type: string
      username:
        type: string
      city:
        type: string
  appointment:
    type: object
    properties:
      id:
        type: integer
      doctor_firstname:
        type: string
      doctor_lastname:
        type: string
      doctor_email:
        type: string
      username:
        type: string
      email:
        type: string
      date_of_appointment:
        type: string
      time_of_appointment:
        type: string
      description:
        type: string
  not_found_error:
    type: object
    properties:
      message:
        type: string
